### ISSUE TITLE
Assets path

### ISSUE THREAD

**Issue by vennamo** [badsyntax/react-seed#11]
If you have any assets-folder in the app/ folder, how do you refer those files? I thought urls like localhost:port/images/file.ext would give me the asset, but it is 404. If you comment the contentBase setting from devServer, then you can access those files from localhost:port/app/images/file.ext. But i'm looking for the way that every folder and file in the app/ folder are treated like the base of the localhost. contentBase: 'app' is something i'm looking for, but you have path.resolve(pkg.config.buildDir) maybe for a reason I don't fully understand.

**Comment by badsyntax** [comment]
Sure, you can set the contentBase to be `app` and the dev server will serve static and compiled files. 

The problem is when you run a production build (via `npm run build`), webpack won't bundle any of those static files, because it doesn't know about them.

To include the files in your build, you want to `require()` all the files you want in your build. 
Refer [to here](https://github.com/badsyntax/react-seed/blob/b995d8f0e1458a0e37763aa95a5fe415ec3975b3/app/app.tests.js)  to see an example of how you can require in full directories. 

I'm not sure what the best solution is here, which is why I've kept the `contentBase` to be the build dir, to force users to `require()` all deps.

**Comment by vennamo** [comment]
Thanks. I'll think about this.

**Comment by vennamo** [comment]
Not sure if this works for me. I need to have assets available without requiring them. Let's say mockup-data for react components via data-urls pointing to json.file or images in components with src='path-to-image' etc.

**Comment by badsyntax** [comment]
You can conditionally require() depending on your `process.env.NODE_ENV` (using ES6 conditional imports won't work, yet).
All images should also be explicitly required (if they are required by your app). Keep in mind the style-loader will automatically copy all images referenced in the CSS.
At the end of the day, whatever works for you, but using a module loader like this means complete dependency management.
